[pytest] #arquivo de configuração do pytest para um projeto.
DJANGO_SETTINGS_MODULE = project.settings #Aqui fica as configurações do meu projeto
python_files = test.py tests.py test_*.py tests_*.py *_test.py *_tests.py #Aqui são os arquivos que devo considerar com test
addopts = #opções que quero que sejam usadas automaticamente todas as vezes que eu executar o pytest
  --doctest-modules
  --strict-markers
  -rP
markers =
  slow: Run tests that are slow
  fast: Run fast tests